# Generated by Django 5.0.6 on 2024-07-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tickets',
        ),
    ]
