# Generated by Django 5.0.6 on 2024-07-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat_number',
            new_name='seat',
        ),
    ]
