# Generated by Django 5.0.6 on 2024-07-11 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_alter_seat_unique_together'),
        ('tickets', '0005_rename_seat_number_ticket_seat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('showtime', 'seat'), name='unique_showtime_seat'),
        ),
    ]
