# Generated by Django 5.0.6 on 2024-07-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_unique_showtime_seat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_showtime_seat',
        ),
    ]
