# Generated by Django 5.0.6 on 2024-07-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_alter_seat_unique_together'),
        ('tickets', '0008_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='halls.seat'),
        ),
    ]
