# Generated by Django 5.0.6 on 2024-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
