# Generated by Django 5.0.6 on 2024-07-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Animación', 'Animación'), ('Aventura', 'Aventura'), ('Biografía', 'Biografía'), ('Ciencia ficción', 'Ciencia ficción'), ('Comedia', 'Comedia'), ('Crimen', 'Crimen'), ('Documental', 'Documental'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Historia', 'Historia'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Suspenso', 'Suspenso'), ('Terror', 'Terror'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
