# Generated by Django 5.0.7 on 2024-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_premiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='carousel_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
