# Generated by Django 5.0.6 on 2024-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_hall_name_alter_seat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='name',
            field=models.CharField(default='', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'name')},
        ),
    ]
