# Generated by Django 5.0.6 on 2024-07-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_seat_name_alter_seat_id_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
