# Generated by Django 5.0.6 on 2024-07-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_alter_seat_unique_together_alter_seat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
