# Generated by Django 5.0.6 on 2024-07-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_alter_seat_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'name')},
        ),
    ]
