# Generated by Django 5.0.6 on 2024-07-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
